### ISSUE TITLE
`ImageSprite` breaks the cache mechanism

### ISSUE THREAD

**Issue by ahyangyi** [citymania-org/grf-py#27]
Hi,

I have noticed that `ImageSprite` does not work when I use at least two instances. It turns out that its fingerprint is `None` and it seems `None` is used as the cache key, causing any two instances of `ImageSprite` to conflict.

At this moment I will work around the issue by subclassing `ImageSprite` (which I was going to do anyways), but I think it's still a bug worth fixing someday.

**Comment by ldpl** [comment]
None was supposed to mean uncacheable but things might have gone wrong, I'll take a look at some point.

**Comment by ahyangyi** [comment]
> None was supposed to mean uncacheable

Thanks for that explanation! I think I understand what's going on, then.

I used constructs in the form of `WithMask(ImageSprite(), ImageSprite())`. Hence, while those `ImageSprite`s themselves are uncacheable, perhaps the cache manager attempted to cache those `WithMask` objects, and saw the same fingerprint?

**Comment by ldpl** [comment]
Oh, yeah, that explains it, `WithMask` fingerpring is just wrong, it doesn't treat those `None`values correctly. 
Either way, I don't like this `None` approach and plan to switch to using exceptions for non-cacheable sprites so this may be a good occasion to actually do that.
